// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AppUser struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Password   string
	LastLogin  sql.NullTime
	FirstName  sql.NullString
	LastName   sql.NullString
	IsStaff    bool
	IsActive   bool
	DateJoined time.Time
}
