// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AppUser struct {
	ID         uuid.UUID    `json:"id"`
	Username   string       `json:"username"`
	Email      string       `json:"email"`
	Password   string       `json:"password"`
	LastLogin  sql.NullTime `json:"last_login"`
	FirstName  string       `json:"first_name"`
	LastName   string       `json:"last_name"`
	IsStaff    bool         `json:"is_staff"`
	IsActive   bool         `json:"is_active"`
	DateJoined time.Time    `json:"date_joined"`
}
