### Get a user by id
GET {{server_url}}/api/user/{{user_id}}/
Accept: application/json
Authorization: Bearer {{access_token}}


### User sign up / Create a user
POST {{server_url}}/auth/sign-up/
Content-Type: application/json

{
  "username": "{{username}}",
  "last_name": "buddy",
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set("user_id", response.body.id);
%}


### Login
POST {{server_url}}/auth/login/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("user_id", response.body.id);
%}


### TokenRefresh
POST {{server_url}}/auth/token-refresh/

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("user_id", response.body.id);
%}

### User self update
PATCH {{server_url}}/api/user/me/
Authorization: Bearer {{access_token}}

{
  "first_name": "new firstname",
  "last_name": "new lastname"
}

### User change password
POST {{server_url}}/api/user/me/password/
Authorization: Bearer {{access_token}}

{
  "old_password": "{{password}}",
  "new_password": "{{password}}"
}

### Send user email verification
POST {{server_url}}/api/user/send-email-verification/
Authorization: Bearer {{access_token}}

### Verify user email verification token
POST {{server_url}}/api/user/verify-email-token/?token=xbcNb3CheZ3okI4hhjLCQLu9Vg3kl%2FiMh9pT%2BQivvgfwk%2BLmOyczBu20l0QViG7%2B8D3Hex%2BsMSFF%2BtGPkTU5LfkJ1TrZL98WSolmpY8%2FPWqObZUGpn6RPrLqapaadbOdcY71SxUsHcgKXPGiJUZuQ%2BJVrSldOPr495MAB15IpUF79lqC5sIEJk1tXMIiNF5e4wRDp5%2FyYZszZQ%3D%3D
Authorization: Bearer {{access_token}}